### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by TessyPowder** [SchoolSquirrel/SchoolSquirrel#5]
@hrueger Should i configure Dependabot for this repository ?

**Comment by hrueger** [comment]
I personally prefer not to because of the following reasons:
- I had quite a few problems when I tried to update the dependencies:
  - `NativeScript` is not yet compatible with `Angular` 10 and it always takes some time until it supports the latest `Angular` version
  - When we update `NativeScript`, the `webpack.config.js` has to be updated very likely, too
  - `nativescript-ui-calendar` must stay version `^5.0.0` because version 6 requires Android 10 and we want to support older versions of Android, too
  - `TypeScript` is always updated before Angular is, so that would break the app very likely
- I personally don't like the massive amount of PRs and commits Dependabot produces (if we don't use it, we can say: `We committed to this project 400 times` but if we use it, probably 1/4 of the commits is dependency upgrades...


I would prefer a GitHub Action, which runs maybe once a week ([docs](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule)). It should read a json file with a list of regexs. The dependencies which match the regexs are ignored, the others are upgraded with [ncu](https://www.npmjs.com/package/npm-check-updates) or [npm-check](https://www.npmjs.com/package/npm-check). The result should be commited to a new branch and a PR should be created.

What do you think @TessyPowder ?

**Comment by TessyPowder** [comment]
You can also ignore specific packages with dependabot: https://github.com/dependabot/feedback/issues/141

**Comment by hrueger** [comment]
I know, but we'd have to ignore quite a lot of stuff... It would make sense for security but I'd prefer manual upgrades. Maybe once it is stable?

**Comment by TessyPowder** [comment]
Ok, that makes sense
